platform :ios,'12.2'
project './VKeyDemo.xcodeproj'
target 'VKeyDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'TCGSDK', :git => "https://github.com/yujunleik/test_pod.git"
  pod 'TCGVKey', :git => "https://github.com/yujunleik/test_pod.git"
end
