platform :ios,'12.2'
project './SimplePCDemo.xcodeproj'
target 'SimplePCDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'TCGSDK', :path => "../../"
end
